# `GenVarLoader`

In [5]:
# Automatically reload code in notebook
%load_ext autoreload
%autoreload 2

import pandas as pd
pd.set_option("display.max_columns", None)
import sys
sys.path.append("code")
import src.pyensembl as PYE
import src.genvarloader as GVL
import genvarloader as gvl


import os
os.chdir("/grid/koo/home/schilder/projects/GenomeEncoder/data")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
mane = PYE.get_mane_transcripts()
mane.head()

19284 MANE transcripts found.

,#NCBI_GeneID,Ensembl_Gene,HGNC_ID,symbol,name,RefSeq_nuc,RefSeq_prot,Ensembl_nuc,Ensembl_prot,MANE_status,GRCh38_chr,chr_start,chr_end,chr_strand,TranscriptId
0,GeneID:1,ENSG00000121410.13,HGNC:5,A1BG,alpha-1-B glycoprotein,NM_130786.4,NP_570602.2,ENST00000263100.8,ENSP00000263100.2,MANE Select,NC_000019.10,58345183,58353492,-,ENST00000263100
1,GeneID:2,ENSG00000175899.15,HGNC:7,A2M,alpha-2-macroglobulin,NM_000014.6,NP_000005.3,ENST00000318602.12,ENSP00000323929.8,MANE Select,NC_000012.12,9067708,9115919,-,ENST00000318602
2,GeneID:9,ENSG00000171428.15,HGNC:7645,NAT1,N-acetyltransferase 1,NM_000662.8,NP_000653.3,ENST00000307719.9,ENSP00000307218.4,MANE Select,NC_000008.11,18210109,18223689,+,ENST00000307719
3,GeneID:10,ENSG00000156006.5,HGNC:7646,NAT2,N-acetyltransferase 2,NM_000015.3,NP_000006.2,ENST00000286479.4,ENSP00000286479.3,MANE Select,NC_000008.11,18391282,18401218,+,ENST00000286479
4,GeneID:12,ENSG00000196136.18,HGNC:16,SERPINA3,serpin family A member 3,NM_001085.5,NP_001076.2,ENST00000393078.5,ENSP00000376793.3,MANE Select,NC_000014.9,94612391,94624053,+,ENST00000393078

In [11]:
db = PYE.get_db()

In [ ]:
transcripts = PYE.get_protein_coding_transcripts()
transcripts = PYE.filter_transcripts(transcripts, ids=mane.TranscriptId.tolist())

Retrieving transcripts.:  16%|█▌        | 17782/111163 [04:08<5:42:25,  4.55it/s]

In [ ]:
bed = gvl.read_bedlike(bed_path)

In [6]:
ds = GVL.create_db()

Connecting to database

In [7]:
ds

GVL store geuvadis.chr22.gvl
Is subset: False
# of regions: 8,237
# of samples: 451
Original region length: 32,768
Max jitter: 0
Has genotypes: True
Has tracks: []

In [2]:
tx = PYE.get_transcript("ENST00000379861")

In [5]:
bed = GVL.read_bed()

(412034, 12)

In [ ]:
chr_bed = bed.slice(bed.chrom == "chr22" and bed.TranscriptId is in mane.)
chr_bed.head()

In [10]:
ds.get_bed()

shape: (8_237, 4)
┌───────┬────────────┬──────────┬────────┐
│ chrom ┆ chromStart ┆ chromEnd ┆ strand │
│ ---   ┆ ---        ┆ ---      ┆ ---    │
│ str   ┆ i64        ┆ i64      ┆ str    │
╞═══════╪════════════╪══════════╪════════╡
│ chr22 ┆ 10510370   ┆ 10543138 ┆ -      │
│ chr22 ┆ 10719842   ┆ 10752610 ┆ -      │
│ chr22 ┆ 10731183   ┆ 10763951 ┆ +      │
│ chr22 ┆ 10731202   ┆ 10763970 ┆ +      │
│ chr22 ┆ 10737140   ┆ 10769908 ┆ -      │
│ …     ┆ …          ┆ …        ┆ …      │
│ chr22 ┆ 50770144   ┆ 50802912 ┆ +      │
│ chr22 ┆ 50770409   ┆ 50803177 ┆ +      │
│ chr22 ┆ 50770406   ┆ 50803174 ┆ +      │
│ chr22 ┆ 50781652   ┆ 50814420 ┆ -      │
│ chr22 ┆ 50782504   ┆ 50815272 ┆ +      │
└───────┴────────────┴──────────┴────────┘