# Variant annotation

In [ ]:
import pandas as pd
import myvariant

In [ ]:
# https://docs.myvariant.info/en/latest/doc/data.html#available-fields
mv = myvariant.MyVariantInfo()
mv.get_fields()

In [ ]:
# Query variants in APOE gene with classification and review status
for transcript_id in knownCanonical['TranscriptId'].tolist()[:3]:
    variants = mv.query("BDNF", scopes='clinvar.hg38',assembly='hg38')
    print(f"Found {len(variants['hits'])} variants in {transcript_id}")

Found 10 variants in ENST00000373020
Found 10 variants in ENST00000373031
Found 10 variants in ENST00000371588

### Compare gene metrics

In [ ]:
rgc = pd.read_excel("RGC-ME/41586_2024_7556_MOESM4_ESM.xlsx", sheet_name="table_s2")
rgc.head()

,GeneName,GeneId,TranscriptId,mean,sd,shet_lower,shet_upper,shet_constrained,n,N_total,mutation_rate,MAF,CDS_length,pKO,constraint_group,oe_lof,loeuf,loeuf_underpower,annotations
0,HSPB11,ENSG00000081870,ENST00000194214,0.038708,0.010539,0.023436,0.064243,False,15,1.643240e+06,3.410630e-07,0.000009,435,False,-,0.64467,1.347,0.0,lethal
1,RPL22,ENSG00000116251,ENST00000234875,0.132981,0.074968,0.050899,0.326520,True,4,1.642900e+06,2.946130e-07,0.000002,387,False,-,0.32990,1.036,0.0,"cancer,essential_line"
2,OPRD1,ENSG00000116329,ENST00000234961,0.008655,0.001007,0.006886,0.010856,False,76,1.643860e+06,3.951480e-07,0.000046,1119,True,LO,0.56836,1.193,0.0,ClinVar/HGMD
3,C1orf21,ENSG00000116667,ENST00000235307,0.120590,0.059463,0.051087,0.272217,True,5,1.643923e+06,3.419660e-07,0.000003,366,False,-,0.00000,0.414,0.0,NaN
4,RGS2,ENSG00000116741,ENST00000235382,0.003639,0.000245,0.003191,0.004155,False,222,1.643654e+06,4.884420e-07,0.000135,636,False,-,0.81481,1.417,0.0,"AR,ClinVar/HGMD"

In [ ]:
variant_counts = pd.DataFrame({k:len(set(v)) for k,v in variant_recorder.items()}, index=['variant_count']).T
variant_counts['TranscriptId'] = variant_counts.index.str.split('.').str[0]
variant_counts.head()
# merge on TranscriptId
variant_rgc = rgc.merge(variant_counts, on='TranscriptId', how='inner')
print(variant_rgc.shape)
variant_rgc.head()

(144, 20)

,GeneName,GeneId,TranscriptId,mean,sd,shet_lower,shet_upper,shet_constrained,n,N_total,mutation_rate,MAF,CDS_length,pKO,constraint_group,oe_lof,loeuf,loeuf_underpower,annotations,variant_count
0,BCL2L2,ENSG00000129473,ENST00000250405,0.011744,0.001896,0.008625,0.016013,False,40,1.643884e+06,2.803850e-07,0.000024,582,False,-,0.17414,0.826,0.0,NaN,16
1,DAD1,ENSG00000129562,ENST00000250498,0.024242,0.004953,0.016365,0.035704,False,25,1.643946e+06,3.601990e-07,0.000015,342,False,-,0.44592,1.369,1.0,"lethal,essential_line",4
2,SLC39A2,ENSG00000165794,ENST00000298681,0.000866,0.000029,0.000810,0.000924,False,868,1.643916e+06,4.548690e-07,0.000528,930,True,LO,0.66316,1.196,0.0,NaN,44
3,OR5AU1,ENSG00000169327,ENST00000304418,0.000101,0.000004,0.000093,0.000109,False,570,1.643951e+06,3.277900e-08,0.000347,936,True,LO,1.29240,1.891,0.0,NaN,59
4,RNASE3,ENSG00000169397,ENST00000304639,0.001827,0.000853,0.000820,0.003939,False,6,1.643952e+06,3.970000e-09,0.000004,483,False,LO,NaN,NaN,NaN,"HS,ClinVar/HGMD",23

In [ ]:
# Plot variant count vs RGC-ME  
import plotly.express as px
fig = px.scatter(variant_rgc, x='variant_count', y='n', hover_data=['TranscriptId'])
fig.show()