In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pooch
import polars as pl
import os

In [ ]:
study_index = pd.read_json("https://ftp.ebi.ac.uk/pub/databases/opentargets/genetics/22.02.01/lut/study-index/part-00000-2e5fae34-19dc-4dff-8f46-9d8a6fc11895-c000.json", lines=True)
study_index.head()

,study_id,pub_date,pub_author,trait_reported,ancestry_initial,ancestry_replication,n_initial,n_replication,n_cases,num_assoc_loci,has_sumstats,source,trait_efos,trait_category
0,FINNGEN_R5_AB1_AMOEBIASIS,2021-5-11,FINNGEN_R5,Amoebiasis,[European=197385],[],197385,0,87,0,True,FINNGEN,[EFO_0007144],infectious disease
1,FINNGEN_R5_AB1_ANOGENITAL_HERPES_SIMPLEX,2021-5-11,FINNGEN_R5,Anogenital herpesviral [herpes simplex] infection,[European=213843],[],213843,0,891,0,True,FINNGEN,[EFO_0007282],infectious disease
2,FINNGEN_R5_AB1_ARTHROPOD,2021-5-11,FINNGEN_R5,Arthropod-borne viral fevers and viral haemorr...,[European=218792],[],218792,0,1450,0,True,FINNGEN,"[MONDO_0018087, EFO_0000763]",infectious disease
3,FINNGEN_R5_AB1_ASPERGILLOSIS,2021-5-11,FINNGEN_R5,Aspergillosis,[European=214903],[],214903,0,87,0,True,FINNGEN,[EFO_0007157],infectious disease
4,FINNGEN_R5_AB1_ATYPICAL_CNS_VIRUS,2021-5-11,FINNGEN_R5,Atypical virus infections of central nervous s...,[European=217783],[],217783,0,146,0,True,FINNGEN,[MONDO_0024318],infectious disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1263,FINNGEN_R5_H7_SEVVISIMPMONOC,2021-5-11,FINNGEN_R5,"""Severe visual impairment, monocular""",[European=210946],[],210946,0,80,0,True,FINNGEN,[MONDO_0001941],disease of visual system
1264,FINNGEN_R5_H7_STENOLACRI,2021-5-11,FINNGEN_R5,Stenosis and insufficiency of lacrimal passages,[European=204549],[],204549,0,1318,0,True,FINNGEN,[HP_0000614],phenotype
1265,FINNGEN_R5_H7_STRABISMUS,2021-5-11,FINNGEN_R5,Strabismus,[European=218792],[],218792,0,4620,0,True,FINNGEN,[HP_0000486],phenotype
1266,FINNGEN_R5_H7_STRABNAS,2021-5-11,FINNGEN_R5,Other specified and unspecified strabismus,[European=211071],[],211071,0,140,0,True,FINNGEN,[HP_0000486],phenotype
1267,FINNGEN_R5_H7_STRABOTH,2021-5-11,FINNGEN_R5,Other strabismus,[European=214760],[],214760,0,3829,0,True,FINNGEN,[HP_0000486],phenotype

In [ ]:
v2g_scored = pd.read_parquet("https://ftp.ebi.ac.uk/pub/databases/opentargets/genetics/latest/v2g_scored/part-00000-f45b4766-6956-4139-be15-36bd714f7d47-c000.snappy.parquet")
print(v2g_scored.shape)
v2g_scored.head()

(1000000, 25)

,chr_id,position,ref_allele,alt_allele,gene_id,feature,type_id,source_id,fpred_labels,fpred_scores,fpred_max_label,fpred_max_score,qtl_beta,qtl_se,qtl_pval,qtl_score,interval_score,qtl_score_q,interval_score_q,d,distance_score,distance_score_q,overall_score,source_list,source_score_list
0,1,10291,C,CT,ENSG00000284733,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441387.0,0.000002,0.1,0.006640,[canonical_tss],[0.1]
1,1,54380,T,C,ENSG00000186092,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11039.0,0.000091,1.0,0.066398,[canonical_tss],[1.0]
2,1,55285,T,C,ENSG00000186092,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10134.0,0.000099,1.0,0.066398,[canonical_tss],[1.0]
3,1,63325,T,C,ENSG00000284733,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,388353.0,0.000003,0.2,0.013280,[canonical_tss],[0.2]
4,1,72573,G,T,ENSG00000186092,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7154.0,0.000140,1.0,0.066398,[canonical_tss],[1.0]

In [ ]:
d2v2g_scored = pd.read_parquet("https://ftp.ebi.ac.uk/pub/databases/opentargets/genetics/latest/d2v2g_scored/part-00000-4496e3f4-9708-4c3a-a769-93d95c79b892-c000.snappy.parquet")
print(d2v2g_scored.shape)
d2v2g_scored.head()

(1000000, 64)

,tag_chrom,tag_pos,tag_ref,tag_alt,gene_id,study_id,source,pmid,pub_date,pub_journal,pub_title,pub_author,has_sumstats,trait_reported,trait_efos,ancestry_initial,ancestry_replication,n_initial,n_replication,n_cases,trait_category,num_assoc_loci,lead_chrom,lead_pos,lead_ref,lead_alt,overall_r2,AFR_1000G_prop,AMR_1000G_prop,EAS_1000G_prop,EUR_1000G_prop,SAS_1000G_prop,log10_ABF,posterior_prob,odds_ratio,oddsr_ci_lower,oddsr_ci_upper,direction,beta,beta_ci_lower,beta_ci_upper,pval_mantissa,pval_exponent,pval,feature,type_id,source_id,fpred_labels,fpred_scores,fpred_max_label,fpred_max_score,qtl_beta,qtl_se,qtl_pval,qtl_score,interval_score,qtl_score_q,interval_score_q,d,distance_score,distance_score_q,overall_score,source_list,source_score_list
0,1,901544,G,A,ENSG00000175756,GCST90025945,GCST,PMID:34226706,2021-07-05,Nat Genet,Whole-exome imputation within UK Biobank power...,Barton AR,True,Cystatin C levels,[EFO_0004617],[European=437846],[],437846,NaN,NaN,measurement,607,1,922671,C,T,0.517138,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,-,-0.016747,-0.021301,-0.012194,7.0,-15,7.000000e-15,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,473663.0,0.000002,0.1,0.006640,[canonical_tss],[0.1]
1,1,903007,T,C,ENSG00000078808,GCST90025945,GCST,PMID:34226706,2021-07-05,Nat Genet,Whole-exome imputation within UK Biobank power...,Barton AR,True,Cystatin C levels,[EFO_0004617],[European=437846],[],437846,NaN,NaN,measurement,607,1,922671,C,T,0.517138,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,-,-0.016747,-0.021301,-0.012194,7.0,-15,7.000000e-15,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,329024.0,0.000003,0.3,0.019920,[canonical_tss],[0.3]
2,1,911848,C,T,ENSG00000188290,GCST90025945,GCST,PMID:34226706,2021-07-05,Nat Genet,Whole-exome imputation within UK Biobank power...,Barton AR,True,Cystatin C levels,[EFO_0004617],[European=437846],[],437846,NaN,NaN,measurement,607,1,922671,C,T,0.726337,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,-,-0.016747,-0.021301,-0.012194,7.0,-15,7.000000e-15,CEDAR-NEUTROPHIL_CD15,eqtl,eqtl,[],[],None,NaN,0.324670,0.058582,7.186620e-08,7.143475,NaN,0.4,NaN,NaN,NaN,NaN,0.146076,"[canonical_tss, eqtl]","[0.8, 0.7]"
3,1,911848,C,T,ENSG00000188290,GCST90025945,GCST,PMID:34226706,2021-07-05,Nat Genet,Whole-exome imputation within UK Biobank power...,Barton AR,True,Cystatin C levels,[EFO_0004617],[European=437846],[],437846,NaN,NaN,measurement,607,1,922671,C,T,0.726337,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,-,-0.016747,-0.021301,-0.012194,7.0,-15,7.000000e-15,unspecified,distance,canonical_tss,[],[],None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88324.0,0.000011,0.8,0.146076,"[canonical_tss, eqtl]","[0.8, 0.7]"
4,1,911848,C,T,ENSG00000188290,GCST90025945,GCST,PMID:34226706,2021-07-05,Nat Genet,Whole-exome imputation within UK Biobank power...,Barton AR,True,Cystatin C levels,[EFO_0004617],[European=437846],[],437846,NaN,NaN,measurement,607,1,922671,C,T,0.726337,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,-,-0.016747,-0.021301,-0.012194,7.0,-15,7.000000e-15,eQTLGen-UBERON_0000178,eqtl,eqtl,[],[],None,NaN,0.172752,0.014979,8.974500e-31,30.046990,NaN,0.7,NaN,NaN,NaN,NaN,0.146076,"[canonical_tss, eqtl]","[0.8, 0.7]"

In [ ]:
v2d = pd.read_parquet("https://ftp.ebi.ac.uk/pub/databases/opentargets/genetics/latest/v2d/part-00000-10068dba-939e-4873-be35-780fc4b12fcc-c000.snappy.parquet")
print(v2d.shape)
v2d.head()

(225545, 44)

,study_id,lead_chrom,lead_pos,lead_ref,lead_alt,direction,beta,beta_ci_lower,beta_ci_upper,odds_ratio,oddsr_ci_lower,oddsr_ci_upper,pval_mantissa,pval_exponent,pval,ancestry_initial,ancestry_replication,n_cases,n_initial,n_replication,pmid,pub_author,pub_date,pub_journal,pub_title,has_sumstats,num_assoc_loci,source,trait_reported,trait_efos,trait_category,tag_chrom,tag_pos,tag_ref,tag_alt,overall_r2,pics_95perc_credset,AFR_1000G_prop,AMR_1000G_prop,EAS_1000G_prop,EUR_1000G_prop,SAS_1000G_prop,log10_ABF,posterior_prob
0,GCST006585_950,1,1008088,T,C,+,0.735542,0.530600,0.940484,NaN,NaN,NaN,2.00000,-12,2.000000e-12,[European=3200],[],NaN,3200,NaN,PMID:30072576,Emilsson V,2018-08-02,Science,Co-regulatory networks of human serum proteins...,False,1,GCST,"Blood protein levels [ISG15, 14151_4_3]",[EFO_0007937],measurement,1,978812,G,C,0.595703,False,0.0,0.0,0.000000,1.000000,0.0,NaN,NaN
1,NEALE2_20003_1140867876,1,1010747,GT,G,-,NaN,NaN,NaN,0.346424,0.237266,0.505801,4.02417,-8,4.024170e-08,[European=361141],[],491.0,361141,0.0,None,UKB Neale v2,2018-08-01,None,None,True,6,NEALE,Prozac 20mg capsule | treatment/medication code,[EFO_0007010],measurement,1,978812,G,C,NaN,None,NaN,NaN,NaN,NaN,NaN,4.345352,0.00226
2,GCST90087821,1,1009731,C,T,+,0.707278,0.556401,0.858155,NaN,NaN,NaN,4.00000,-20,4.000000e-20,[European=5366],[],NaN,5366,NaN,PMID:35078996,Gudjonsson A,2022-01-25,Nat Commun,A genome-wide association study of serum prote...,False,2,GCST,Serum levels of protein ISG15,[EFO_0007937],measurement,1,978812,G,C,0.579132,False,0.0,0.0,0.000000,1.000000,0.0,NaN,NaN
3,GCST90095130,1,994997,C,T,+,5.840000,3.882404,7.797596,NaN,NaN,NaN,5.00000,-9,5.000000e-09,[European=33748],[],NaN,33748,NaN,PMID:34910505,van der Meer D,2021-12-15,Sci Adv,The genetic architecture of human cortical fol...,False,669,GCST,Vertex-wise cortical surface area,[EFO_0010736],measurement,1,986629,G,A,0.942542,True,0.0,0.0,0.000000,1.000000,0.0,NaN,NaN
4,GCST90018954,1,993036,G,A,+,0.015400,0.010211,0.020589,NaN,NaN,NaN,6.00000,-9,6.000000e-09,"[European=344104, East Asian=133471]",[],NaN,477575,NaN,PMID:34594039,Sakaue S,2021-09-30,Nat Genet,A cross-population atlas of genetic associatio...,False,305,GCST,Gamma glutamyl transpeptidase,[EFO_0004532],measurement,1,986629,G,A,0.910355,True,0.0,0.0,0.279477,0.720523,0.0,NaN,NaN