# Variant annotation

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import sys
sys.path.append("code")
from src.pyensembl import *     
from src.utils import *
from src.variant_annotation import *
from src.ensembl_rest import *
os.chdir("/grid/koo/home/schilder/projects/GenomeEncoder/data")

In [25]:
mane = get_mane_transcripts()
db = get_db()

19284 MANE transcripts found.

## ClinVar VCF

Take dbSNP/ClinVar variants and create a `pysam.VariantFile` object with them.

In [82]:
cv = get_clinvar_db()
# get_clinvar_db_headers(cv)

In [100]:
info_descriptions = get_clinvar_db_info_descriptions(cv)
info_descriptions

{'AF_ESP': 'allele frequencies from GO-ESP',
 'AF_EXAC': 'allele frequencies from ExAC',
 'AF_TGP': 'allele frequencies from TGP',
 'ALLELEID': 'the ClinVar Allele ID',
 'CLNDN': "ClinVar's preferred disease name for the concept specified by disease identifiers in CLNDISDB",
 'CLNDNINCL': "For included Variant : ClinVar's preferred disease name for the concept specified by disease identifiers in CLNDISDB",
 'CLNDISDB': 'Tag-value pairs of disease database name and identifier submitted for germline classifications, e.g. OMIM:NNNNNN',
 'CLNDISDBINCL': 'For included Variant: Tag-value pairs of disease database name and identifier for germline classifications, e.g. OMIM:NNNNNN',
 'CLNHGVS': 'Top-level (primary assembly, alt, or patch) HGVS expression.',
 'CLNREVSTAT': 'ClinVar review status of germline classification for the Variation ID',
 'CLNSIG': 'Aggregate germline classification for this single variant; multiple values are separated by a vertical bar',
 'CLNSIGCONF': 'Conflicting germline classification for this single variant; multiple values are separated by a vertical bar',
 'CLNSIGINCL': 'Germline classification for a haplotype or genotype that includes this variant. Reported as pairs of VariationID:classification; multiple values are separated by a vertical bar',
 'CLNVC': 'Variant type',
 'CLNVCSO': 'Sequence Ontology id for variant type',
 'CLNVI': "the variant's clinical sources reported as tag-value pairs of database and variant identifier",
 'DBVARID': 'nsv accessions from dbVar for the variant',
 'GENEINFO': 'Gene(s) for the variant reported as gene symbol:gene id. The gene symbol and id are delimited by a colon (:) and each pair is delimited by a vertical bar (|)',
 'MC': 'comma separated list of molecular consequence in the form of Sequence Ontology ID|molecular_consequence',
 'ONCDN': "ClinVar's preferred disease name for the concept specified by disease identifiers in ONCDISDB",
 'ONCDNINCL': "For included variant: ClinVar's preferred disease name for the concept specified by disease identifiers in ONCDISDBINCL",
 'ONCDISDB': 'Tag-value pairs of disease database name and identifier submitted for oncogenicity classifications, e.g. MedGen:NNNNNN',
 'ONCDISDBINCL': 'For included variant: Tag-value pairs of disease database name and identifier for oncogenicity classifications, e.g. OMIM:NNNNNN',
 'ONC': 'Aggregate oncogenicity classification for this single variant; multiple values are separated by a vertical bar',
 'ONCINCL': 'Oncogenicity classification for a haplotype or genotype that includes this variant. Reported as pairs of VariationID:classification; multiple values are separated by a vertical bar',
 'ONCREVSTAT': 'ClinVar review status of oncogenicity classification for the Variation ID',
 'ONCCONF': 'Conflicting oncogenicity classification for this single variant; multiple values are separated by a vertical bar',
 'ORIGIN': 'Allele origin. One or more of the following values may be added: 0 - unknown; 1 - germline; 2 - somatic; 4 - inherited; 8 - paternal; 16 - maternal; 32 - de-novo; 64 - biparental; 128 - uniparental; 256 - not-tested; 512 - tested-inconclusive; 1073741824 - other',
 'RS': 'dbSNP ID (i.e. rs number)',
 'SCIDN': "ClinVar's preferred disease name for the concept specified by disease identifiers in SCIDISDB",
 'SCIDNINCL': "For included variant: ClinVar's preferred disease name for the concept specified by disease identifiers in SCIDISDBINCL",
 'SCIDISDB': 'Tag-value pairs of disease database name and identifier submitted for somatic clinial impact classifications, e.g. MedGen:NNNNNN',
 'SCIDISDBINCL': 'For included variant: Tag-value pairs of disease database name and identifier for somatic clinical impact classifications, e.g. OMIM:NNNNNN',
 'SCIREVSTAT': 'ClinVar review status of somatic clinical impact for the Variation ID',
 'SCI': 'Aggregate somatic clinical impact for this single variant; multiple values are separated by a vertical bar',
 'SCIINCL': 'Somatic clinical impact classification for a haplotype or genotype that includes this variant. Reported as pairs of VariationID:classification; multiple values are separated by a vertical bar'}

### Pathogenic variants

In [136]:
variants_pathogenic = get_clinvar_variants_pathogenic(
    db=db,
    cv=cv,
    transcript_ids= mane['TranscriptId'].tolist(),
    min_variants_per_transcript=1,
    max_variants_per_transcript=1,
    mc_descendants='missense_variant',
    save_path="clinvar/mane_clinvar_variants_pathogenic.vcf.gz",
    )

Found 6 descendants of 'missense_variant'
Using existing file: clinvar/mane_clinvar_variants_pathogenic.vcf.gz

Fetching clinvar variants:   0%|          | 0/19284 [00:00<?, ?it/s]

Sorting variants:   0%|          | 0/1242 [00:00<?, ?it/s]

Selected 80 transcripts.

Selecting variants:   0%|          | 0/1242 [00:00<?, ?it/s]

Selected 80 variants.

In [103]:
variants_pathogenic['recs_selected'][0].info.items()

[('ALLELEID', 166563),
 ('CLNDISDB',
  ('MONDO:MONDO:0100283',
   'MedGen:CN300503|MedGen:C3661900|Human_Phenotype_Ontology:HP:0032051',
   'MONDO:MONDO:0011818',
   'MedGen:C1846385',
   'OMIM:607341',
   'Orphanet:268994')),
 ('CLNDN',
  ('Overgrowth_syndrome_and/or_cerebral_malformations_due_to_abnormalities_in_MTOR_pathway_genes|not_provided|Isolated_focal_cortical_dysplasia_type_II',)),
 ('CLNHGVS', ('NC_000001.11:g.11124516G>A',)),
 ('CLNREVSTAT', ('reviewed_by_expert_panel',)),
 ('CLNSIG', ('Pathogenic',)),
 ('CLNVC', 'single_nucleotide_variant'),
 ('CLNVCSO', 'SO:0001483'),
 ('CLNVI', ('ClinGen:CA248393|OMIM:601231.0008',)),
 ('GENEINFO', 'MTOR:2475'),
 ('MC', ('SO:0001583|missense_variant',)),
 ('ORIGIN', ('3',)),
 ('RS', ('587777894',)),
 ('transcript_id', 'ENST00000361445')]

### Benign variants

In [137]:
variants_benign = get_clinvar_variants_benign(
    db=db,
    cv=cv,
    transcript_ids= mane['TranscriptId'].tolist(),
    min_variants_per_transcript=1,
    max_variants_per_transcript=1,
    mc_descendants='missense_variant',
    save_path="clinvar/mane_clinvar_variants_benign.vcf.gz",
    )

Found 6 descendants of 'missense_variant'
Using existing file: clinvar/mane_clinvar_variants_benign.vcf.gz

Fetching clinvar variants:   0%|          | 0/19284 [00:00<?, ?it/s]

Sorting variants:   0%|          | 0/789 [00:00<?, ?it/s]

Selected 71 transcripts.

Selecting variants:   0%|          | 0/789 [00:00<?, ?it/s]

Selected 71 variants.

In [140]:
transcript_ids = intersect(variants_pathogenic['transcripts_selected'].keys(), 
                           variants_benign['transcripts_selected'].keys())

In [141]:
transcript_to_gene(transcript_ids)

{'ENST00000372874': 'ADA',
 'ENST00000252288': 'GAMT',
 'ENST00000037502': 'MYOC',
 'ENST00000351677': 'PTPN11',
 'ENST00000356839': 'ACADVL',
 'ENST00000234420': 'MSH6',
 'ENST00000302262': 'GAA',
 'ENST00000380152': 'BRCA2',
 'ENST00000262407': 'ITGA2B',
 'ENST00000558518': 'LDLR',
 'ENST00000263967': 'PIK3CA',
 'ENST00000313071': 'FOXG1',
 'ENST00000422285': 'PDHA1',
 'ENST00000257555': 'HNF1A',
 'ENST00000354534': 'SCN8A',
 'ENST00000646891': 'BRAF',
 'ENST00000631182': 'SCN2A',
 'ENST00000316673': 'HNF4A',
 'ENST00000417302': 'HRAS',
 'ENST00000251849': 'RAF1',
 'ENST00000354452': 'TCF4',
 'ENST00000269305': 'TP53',
 'ENST00000218099': 'F9',
 'ENST00000311485': 'RAG2',
 'ENST00000316623': 'FBN1',
 'ENST00000357654': 'BRCA1',
 'ENST00000261769': 'CDH1',
 'ENST00000453960': 'MECP2',
 'ENST00000644269': 'SLC26A4',
 'ENST00000675843': 'ATM',
 'ENST00000375437': 'SCN2A',
 'ENST00000623535': 'CDKL5',
 'ENST00000360256': 'F8',
 'ENST00000402219': 'SOS1',
 'ENST00000256474': 'VHL',
 'ENST00000370396': 'MTM1',
 'ENST00000627620': 'SCN8A',
 'ENST00000644969': 'BRAF',
 'ENST00000389253': 'DNM2',
 'ENST00000311189': 'HRAS',
 'ENST00000231790': 'MLH1',
 'ENST00000303391': 'MECP2',
 'ENST00000262340': 'RPE65',
 'ENST00000579795': 'FOXN1',
 'ENST00000675419': 'RUNX1',
 'ENST00000303115': 'IL7R',
 'ENST00000403799': 'GCK',
 'ENST00000378278': 'DCLRE1C',
 'ENST00000307340': 'USH2A',
 'ENST00000233146': 'MSH2',
 'ENST00000369452': 'SHOC2',
 'ENST00000355349': 'MYH7',
 'ENST00000262948': 'MAP2K2',
 'ENST00000373203': 'ENG',
 'ENST00000359596': 'RYR1',
 'ENST00000253122': 'SLC6A8',
 'ENST00000343455': 'DICER1',
 'ENST00000224721': 'CDH23',
 'ENST00000559488': 'ITGB3'}

In [19]:
import os
os.chdir("/grid/koo/home/schilder/projects/GenomeEncoder/data")

# Load the Reference Genome
vcf_files = list_vcf()

23 VCF files found.

In [20]:
results_wt = personalize_seqs(vcf_files, 
                               ref_genome = "GRCh38/GRCh38_full_analysis_set_plus_decoy_hla.fa",
                               save_dir = "1KG/sequence_dict_all_tmp",
                               max_files = 1,
                               max_samples = 10,
                               max_transcripts = 10,
                               transcript_ids = transcript_ids,
                               max_workers = 1,
                               force = True
                               )

Processing VCF files:   0%|          | 0/1 [00:00<?, ?it/s]

Processing chr14 transcripts:   0%|          | 0/3 [00:00<?, ?it/s]

ENST00000313071: Processing 11 samples:   0%|          | 0/11 [00:00<?, ?it/s]

/grid/koo/home/schilder/.local/lib/python3.9/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

ENST00000343455: Processing 11 samples:   0%|          | 0/11 [00:00<?, ?it/s]

ENST00000355349: Processing 11 samples:   0%|          | 0/11 [00:00<?, ?it/s]

Converting all results to dict.

In [21]:


results_cv = personalize_seqs(vcf_files, 
                               ref_genome = "GRCh38/GRCh38_full_analysis_set_plus_decoy_hla.fa",
                               save_dir = "1KG/sequence_dict_all_extra_variants",
                               max_files = 1,
                               max_samples = 10,
                               max_transcripts = 10,
                               extra_variants = recs_selected, # CLINVAR variants
                               transcript_ids = list(transcripts_selected.keys()),
                               max_workers = 1,
                               force = True
                               )

Processing VCF files:   0%|          | 0/1 [00:00<?, ?it/s]

Processing chr14 transcripts:   0%|          | 0/3 [00:00<?, ?it/s]

ENST00000313071: Processing 11 samples:   0%|          | 0/11 [00:00<?, ?it/s]

/grid/koo/home/schilder/.local/lib/python3.9/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

ENST00000343455: Processing 11 samples:   0%|          | 0/11 [00:00<?, ?it/s]

ENST00000355349: Processing 11 samples:   0%|          | 0/11 [00:00<?, ?it/s]

Converting all results to dict.

## 1KG: precomputed

### Summary table

In [55]:
# https://www.internationalgenome.org/category/annotation/

import pandas as pd
anno = pd.read_csv("https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/functional_annotation/filtered/functional_categories_summary_per_individual.20150208.txt", sep="\t")
anno.head()

,CONSEQUENCE_TYPE,SUP_POP,POP_NAME,IND_NAME,ACCESSIBILITY,Freq_BIN,SITE_COUNT,HOM_COUNT,HET_COUNT,ALLELE_COUNT
0,TF_binding_site_variant,EAS,KHV,HG01595,Accessible,0.5%-5%,23,2,22,24
1,TF_binding_site_variant,EAS,KHV,HG01595,Accessible,>5%,496,246,373,619
2,TF_binding_site_variant,EAS,KHV,HG01595,Accessible,singleton,5,0,5,5
3,TF_binding_site_variant,EAS,KHV,HG01595,Accessible,singleton-0.5%,16,0,16,16
4,TF_binding_site_variant,EAS,KHV,HG01595,Inaccessible,0.5%-5%,0,0,0,0

In [78]:
mut_counts = anno.groupby(['CONSEQUENCE_TYPE','IND_NAME'])['ALLELE_COUNT'].sum().groupby(['CONSEQUENCE_TYPE']).describe().round(2)
mut_counts.to_csv("1KG/1KG_mutation_summary.csv")
mut_counts

,count,mean,std,min,25%,50%,75%,max
CONSEQUENCE_TYPE,,,,,,,,
3_prime_UTR_variant,2504.0,22611.42,1691.28,20516.0,21464.00,21731.5,24889.00,26153.0
5_prime_UTR_variant,2504.0,5020.58,376.85,4535.0,4760.00,4839.0,5481.00,5910.0
CLINVAR_clnsig=4,2236.0,2.23,1.02,1.0,1.00,2.0,3.00,6.0
CLINVAR_clnsig=5,2504.0,32.55,5.49,16.0,29.00,32.0,36.00,55.0
FunSeq_score>1.5,2504.0,42221.12,3167.34,38258.0,40047.00,40614.5,46551.25,48682.0
GWAS,2504.0,1621.96,39.83,1495.0,1594.00,1618.0,1651.00,1745.0
HGMD-DM,2504.0,21.41,4.66,7.0,18.00,21.0,24.00,40.0
Large_Deletion_NON_OVERLAP_GENE,2504.0,479.01,19.86,418.0,465.00,478.0,492.00,561.0
Large_Deletion_OVERLAP_GENE,2504.0,702.56,35.08,607.0,678.00,699.0,724.00,993.0
PHOSPHORYLATION_evidence<=5,2504.0,77.76,8.82,47.0,71.00,77.0,84.00,113.0
PHOSPHORYLATION_evidence>5,2504.0,5.65,2.28,1.0,4.00,5.0,7.00,15.0
TF_binding_site_variant,2504.0,702.51,57.95,595.0,661.00,681.0,752.25,880.0
all_SNPs,2504.0,2567834.81,177527.28,2372431.0,2446082.25,2474339.0,2811659.75,2909698.0
ctcf_insulator,2504.0,51657.08,3766.12,47152.0,49071.00,49708.0,56827.25,58993.0
distal_enhancer,2504.0,48992.02,3565.38,44822.0,46568.75,47120.0,53913.75,55873.0
frameshift_variant,2504.0,271.67,15.78,233.0,260.75,269.0,281.00,333.0
frameshift_variant_aloft,2504.0,145.93,12.32,115.0,137.00,144.0,154.00,201.0
inframe,2504.0,336.36,19.89,285.0,322.00,333.0,349.00,417.0
intergenic_variant,2504.0,1201314.01,79268.63,1112358.0,1147341.25,1159253.0,1309401.50,1357350.0
intron_variant,2504.0,1577306.24,113177.19,1446721.0,1499758.50,1518347.5,1735605.25,1794250.0
missense_variant,2504.0,8641.24,533.28,7806.0,8271.75,8396.0,9285.75,9953.0
promoter,2504.0,75315.84,5647.08,68882.0,71373.50,72442.5,83042.25,86716.0
proximal_enhancer,2504.0,217392.81,15723.66,199145.0,206605.75,209336.0,239267.50,247388.0
regulatory_region_variant,2504.0,79703.04,5605.71,73316.0,75873.75,76800.0,87186.50,90810.0
small_indel,2504.0,799816.10,31063.56,762093.0,779445.50,787377.5,835050.50,859676.0
splice_acceptor_variant,2375.0,3.31,1.34,1.0,2.00,3.0,4.00,8.0
splice_acceptor_variant_aloft,2504.0,27.71,6.50,8.0,24.00,28.0,32.00,50.0
splice_donor_variant,2475.0,3.57,1.45,1.0,3.00,3.0,5.00,9.0
splice_donor_variant_aloft,2504.0,26.06,7.19,6.0,20.00,26.0,30.00,54.0
stop_gained,2504.0,70.79,8.56,46.0,65.00,70.0,76.00,100.0
stop_gained_aloft,2504.0,118.88,15.19,76.0,108.00,118.0,128.00,174.0
stop_lost,2504.0,10.63,2.79,2.0,9.00,10.0,12.00,21.0
synonymous_variant,2504.0,10154.90,752.45,9193.0,9639.75,9768.5,11151.00,11761.0
unannotated_tfbs,2504.0,22177.27,1736.65,20300.0,20982.75,21273.0,24569.00,25633.0

### Annotation VCFs

In [81]:
from src.onekg import *
vcf = get_annotation_vcf("chr22")
recs = [rec for rec in vcf.fetch("22", 22125503, 22125504)]
recs

[]

## `ensembl_rest`

In [52]:
from src.ensembl_rest import *

In [54]:

import pysam
rec = pysam.VariantRecord(contig="9", pos=22125503, ref="A", alt="C")
get_vep(rec=rec, allele="C")

TypeError: this class cannot be instantiated from Python

## `myvariant`

In [2]:
# See here for an explanation of each field: 
# https://useast.ensembl.org/info/genome/variation/prediction/protein_function.html
mv = get_mv_db()
fields = mv.get_fields()
tx_fields = find_field('consequence')
tx_fields

['cadd.consequence']

In [101]:
pd.set_option('display.max_columns', None)

variants_df = pd.DataFrame()
for transcript_id in mane['TranscriptId'].tolist()[:3]:
    tx = db.transcript_by_id(transcript_id)
    ranges =[f"chr{tx.contig}:{range[0]}-{range[1]}" for range in tx.coding_sequence_position_ranges]
    variant_df_i = mv.query(q=ranges,
        # f"dbnsfp.ensembl.transcriptid:{transcript_id}",
                        #  scopes=['clinvar'],
                         fields='all',  # Specify additional fields as needed
                         assembly='hg38',
                         as_dataframe=True)
    variant_df_i.insert(0, 'transcript_id', transcript_id)
    variants_df = pd.concat([variants_df, variant_df_i])
    print(f"Found {len(variant_df_i)} variants in {transcript_id}")
print(variants_df.shape)

Found 10 variants in ENST00000373020
Found 10 variants in ENST00000373031
Found 10 variants in ENST00000371588
(30, 647)

In [108]:
# drop cols with all nan
# variants_df.dropna(axis=1, how='all').head(50)
# view only clinvar columns
# clinvar_cols = [col for col in variants_df.columns if 'clinvar' in col]
# variants_df[clinvar_cols]
variants_df.columns.tolist()
variants_df.head(10)

# snpeff.ann.putative_impact

KeyError: 'cadd.consequence'

## EMBL-EBI Proteins API

In [19]:
pd.set_option('display.max_columns', None)
embl_res = embl_get_variants('O43657')
embl_res.loc[embl_res['clinicalSignificances'].notna(),]

,accession,entryName,proteinName,geneName,organismName,proteinExistence,sequence,sequenceChecksum,sequenceVersion,taxid,type,alternativeSequence,begin,end,xrefs,cytogeneticBand,genomicLocation,locations,codon,consequenceType,wildType,mutatedType,predictions,somaticStatus,sourceType,descriptions,clinicalSignificances,ftId,evidences,populationFrequencies
15,O43657,TSN6_HUMAN,Tetraspanin-6,TSPAN6,Homo sapiens,Evidence at protein level,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...,9304343482296458210,1,9606,VARIANT,I,10,10,"[{'name': 'ExAC', 'id': 'rs752076056', 'url': ...",Xq22.1,[NC_000023.11:g.100636666G>A],"[{'loc': 'p.Thr10Ile', 'seqId': 'ENST000003730...",ACT/ATT,missense,T,I,"[{'predictionValType': 'possibly damaging', 'p...",0,large_scale_study,NaN,"[{'type': 'Variant of uncertain significance',...",NaN,NaN,NaN
58,O43657,TSN6_HUMAN,Tetraspanin-6,TSPAN6,Homo sapiens,Evidence at protein level,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...,9304343482296458210,1,9606,VARIANT,L,63,63,"[{'name': 'ExAC', 'id': 'rs767429263', 'url': ...",Xq22.1,[NC_000023.11:g.100635647C>G],"[{'loc': 'p.Val63Leu', 'seqId': 'ENST000003730...",GTG/CTG,missense,V,L,"[{'predictionValType': 'benign', 'predictorTyp...",0,large_scale_study,NaN,"[{'type': 'Variant of uncertain significance',...",NaN,NaN,NaN
75,O43657,TSN6_HUMAN,Tetraspanin-6,TSPAN6,Homo sapiens,Evidence at protein level,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...,9304343482296458210,1,9606,VARIANT,T,87,87,"[{'name': '1000Genomes', 'id': 'rs145821935', ...",Xq22.1,[NC_000023.11:g.100635575C>T],"[{'loc': 'p.Ala87Thr', 'seqId': 'ENST000003730...",GCA/ACA,missense,A,T,"[{'predictionValType': 'benign', 'predictorTyp...",0,large_scale_study,NaN,"[{'type': 'Likely benign', 'sources': ['Ensemb...",NaN,NaN,NaN
109,O43657,TSN6_HUMAN,Tetraspanin-6,TSPAN6,Homo sapiens,Evidence at protein level,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...,9304343482296458210,1,9606,VARIANT,H,132,132,"[{'name': '1000Genomes', 'id': 'rs189159745', ...",Xq22.1,[NC_000023.11:g.100633985C>G],"[{'loc': 'p.Gln132His', 'seqId': 'ENST00000373...",CAG/CAC,missense,Q,H,"[{'predictionValType': 'benign', 'predictorTyp...",0,large_scale_study,NaN,"[{'type': 'Benign', 'sources': ['Ensembl']}]",NaN,NaN,NaN

### Compare gene metrics

In [ ]:
rgc = pd.read_excel("RGC-ME/41586_2024_7556_MOESM4_ESM.xlsx", sheet_name="table_s2")
rgc.head()

,GeneName,GeneId,TranscriptId,mean,sd,shet_lower,shet_upper,shet_constrained,n,N_total,mutation_rate,MAF,CDS_length,pKO,constraint_group,oe_lof,loeuf,loeuf_underpower,annotations
0,HSPB11,ENSG00000081870,ENST00000194214,0.038708,0.010539,0.023436,0.064243,False,15,1.643240e+06,3.410630e-07,0.000009,435,False,-,0.64467,1.347,0.0,lethal
1,RPL22,ENSG00000116251,ENST00000234875,0.132981,0.074968,0.050899,0.326520,True,4,1.642900e+06,2.946130e-07,0.000002,387,False,-,0.32990,1.036,0.0,"cancer,essential_line"
2,OPRD1,ENSG00000116329,ENST00000234961,0.008655,0.001007,0.006886,0.010856,False,76,1.643860e+06,3.951480e-07,0.000046,1119,True,LO,0.56836,1.193,0.0,ClinVar/HGMD
3,C1orf21,ENSG00000116667,ENST00000235307,0.120590,0.059463,0.051087,0.272217,True,5,1.643923e+06,3.419660e-07,0.000003,366,False,-,0.00000,0.414,0.0,NaN
4,RGS2,ENSG00000116741,ENST00000235382,0.003639,0.000245,0.003191,0.004155,False,222,1.643654e+06,4.884420e-07,0.000135,636,False,-,0.81481,1.417,0.0,"AR,ClinVar/HGMD"

In [ ]:
variant_counts = pd.DataFrame({k:len(set(v)) for k,v in variant_recorder.items()}, index=['variant_count']).T
variant_counts['TranscriptId'] = variant_counts.index.str.split('.').str[0]
variant_counts.head()
# merge on TranscriptId
variant_rgc = rgc.merge(variant_counts, on='TranscriptId', how='inner')
print(variant_rgc.shape)
variant_rgc.head()

(144, 20)

,GeneName,GeneId,TranscriptId,mean,sd,shet_lower,shet_upper,shet_constrained,n,N_total,mutation_rate,MAF,CDS_length,pKO,constraint_group,oe_lof,loeuf,loeuf_underpower,annotations,variant_count
0,BCL2L2,ENSG00000129473,ENST00000250405,0.011744,0.001896,0.008625,0.016013,False,40,1.643884e+06,2.803850e-07,0.000024,582,False,-,0.17414,0.826,0.0,NaN,16
1,DAD1,ENSG00000129562,ENST00000250498,0.024242,0.004953,0.016365,0.035704,False,25,1.643946e+06,3.601990e-07,0.000015,342,False,-,0.44592,1.369,1.0,"lethal,essential_line",4
2,SLC39A2,ENSG00000165794,ENST00000298681,0.000866,0.000029,0.000810,0.000924,False,868,1.643916e+06,4.548690e-07,0.000528,930,True,LO,0.66316,1.196,0.0,NaN,44
3,OR5AU1,ENSG00000169327,ENST00000304418,0.000101,0.000004,0.000093,0.000109,False,570,1.643951e+06,3.277900e-08,0.000347,936,True,LO,1.29240,1.891,0.0,NaN,59
4,RNASE3,ENSG00000169397,ENST00000304639,0.001827,0.000853,0.000820,0.003939,False,6,1.643952e+06,3.970000e-09,0.000004,483,False,LO,NaN,NaN,NaN,"HS,ClinVar/HGMD",23

In [ ]:
# Plot variant count vs RGC-ME  
import plotly.express as px
fig = px.scatter(variant_rgc, x='variant_count', y='n', hover_data=['TranscriptId'])
fig.show()

## Deep Mutational Scanning

A collection of DMS experiment results from [Riesselman et al. 2018 (ie. theDeepSequence paper)](https://www.nature.com/articles/s41592-018-0138-4#MOESM4).

In [1]:
import attr, os
from pprint import PrettyPrinter
from mavetools.client.client import Client
from mavetools.models.experiment import Experiment
pp = PrettyPrinter(indent=2)  # displayes results in readable format

In [17]:
base_url = 'https://www.mavedb.org/api/'
experiment_urn = 'urn:mavedb:00000001-a'

# Set the environment variable
auth_token = os.getenv('MAVEDB_TOKEN')
client = Client(base_url, auth_token=auth_token)

In [21]:
auth_token

'WSA1PioH6McSPWSasI_F0DjVL4l0SRBqqRIJqle88TM'

In [18]:
experiment = client.get_model_instance(Experiment, experiment_urn)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)